### PR TITLE
window is not defined

### PR DESCRIPTION
**Pull request by nickbreaton**
Hello! Thanks for this awesome library. I just started playing with it on a side project and I'm really enjoying it so far.

This is kind of an odd PR, but bear with me. As I was developing, I added your library to some code in a WebWorker, and the [`window` object is actually not defined there](https://stackoverflow.com/questions/11219775/global-variable-in-web-worker). I see you were doing a check to see if `window` contains a value, but not checking if `window` itself is defined. 

Luckily there is a super easy fix! Thanks again.

### CODE REVIEW

**Comment by nickbreaton** [comment]
Ugh let me fix some whitespace issues I created. Whoops.

**Comment by anish000kumar** [comment]
Hey! Thanks for submitting the PR. Can you share a code snippet where you faced the issue, and how may I reproduce it?

**Comment by nickbreaton** [comment]
Hey it is a little tricky to stick this into a snippet since a module bundler is probably the easiest way to get this reproduced. I just made an additional branch on my fork showing the issue. The following steps should produce the error for you:

1.  ```
    git clone https://github.com/nickbreaton/redux-box
    git checkout issue-snippet
    npm install
    npm start
    ```
2. Go to [http://localhost:8080/](http://localhost:8080/)

3. Open dev tools to see following error:


![](https://i.imgur.com/XxC9bzD.png)

**Comment by nickbreaton** [comment]
The same issue will also occur in node with the following file:

```js
// index.js
require('redux-box')
```

Then run:
```
node index.js
```

This results in:
```
var devTools = window && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__;
               ^

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/nick/Code/redux-box/node_modules/redux-box/dist/index.js:41:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nick/Code/redux-box/index.js:1:63)
    at Module._compile (module.js:660:30)
```

**Comment by anish000kumar** [comment]
Thanks for the snippets! Merged the PR!

**Pull request merged**
